### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by birdmod** [aloisdg/diab#27]
What about a dark theme ? Do you think this could appeal to users ? 
If yes the background will need to be processed before being sent to the printer otherwise ... 🖨️ 😠

**Comment by KimClarisse** [comment]
Hello, this project uses water.css which includes both a dark and light theme. I have a dark theme enabled for my browser so it's the dark one that's set by default for me.

-------- Message d'origine --------

**Comment by aloisdg** [comment]
Indeed [water.css](https://watercss.kognise.dev/) handles the UI. By default water.css is set to automatic:

![image](https://user-images.githubusercontent.com/3449303/95958726-d5d20880-0e01-11eb-81f5-0e3d083399ae.png)

and the documentation says:

![image](https://user-images.githubusercontent.com/3449303/95958802-f4d09a80-0e01-11eb-90fb-74a5dcc65f63.png)

Since I enabled the setting in my browser too, here is what I see:

![image](https://user-images.githubusercontent.com/3449303/95958928-1c276780-0e02-11eb-98b8-c950a87de118.png)

On day we will leave water.css and navigate in our own water, handmade style with tailwindcss I guess. We will see.

**Comment by aloisdg** [comment]
Note that we could add a moon/sun icon on the top/right corner to manually to the switch. This would be a whole other issue though.

Thank you all for the comments :)
